name: Java CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 15
        uses: actions/setup-java@v3
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots package

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          JAVA_FILE_NAME: checkstyle.xml

